### ISSUE TITLE
[FEATURE] Add documentation using Docusaurus and GitHub Pages

### ISSUE THREAD

**Issue by guibranco** [guibranco/VTEX-SDK-dotnet#19]
**Is your feature request related to a problem? Please describe.**  
The project currently lacks adequate documentation, which hinders users from understanding how to utilize the library effectively. Comprehensive documentation, including usage examples, is essential for improving user experience and promoting wider adoption.

**Describe the solution you'd like**  
Implement documentation for the project using Docusaurus and host it on GitHub Pages. This documentation should include clear usage examples to illustrate how to effectively use the library.

**Proposed Steps**  
1. **Set Up Docusaurus**: 
   - Initialize a Docusaurus project in a `docs` directory.
   - Configure the Docusaurus settings to align with the project branding.

2. **Create Documentation Content**:
   - Write detailed documentation covering the library's features and functionalities.
   - Include usage examples that demonstrate common use cases and best practices.

3. **Deploy to GitHub Pages**:
   - Use GitHub Actions to automate the build and deployment process for the Docusaurus documentation to GitHub Pages.

**Links**  
- [Docusaurus Documentation](https://docusaurus.io/docs)
- [Docusaurus Installation Guide](https://docusaurus.io/docs/installation)

**Example Code Snippet to Install Docusaurus**:
```bash
npx create-docusaurus@latest my-website classic
cd my-website
npm run start
```

**GitHub Actions Workflow**  
Below is an example of a GitHub Actions workflow to build and push the documentation to the `gh-pages` branch of the repository:

```yaml
name: Deploy Documentation

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: |
        npm install
        npm run build  # Build the Docusaurus site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages  # Specify the branch to publish
```

**Additional Context**  
Using Docusaurus will allow for a modern and maintainable documentation site, enhancing accessibility for users. The GitHub Actions workflow ensures that updates to the documentation are automatically deployed with every push to the main branch.
